# Generated by Django 5.1.1 on 2025-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0025_alter_portfolio_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='checking_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='level_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='level_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='level_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='level_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
