# Generated by Django 5.1.1 on 2025-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0026_portfolio_checking_total_portfolio_level_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
