# Generated by Django 5.1.1 on 2025-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0028_portfolio_card_available_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='apartment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tax_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
