# Generated by Django 5.1.1 on 2025-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0029_portfolio_apartment_portfolio_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='government_ids/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
