# Generated by Django 5.1.1 on 2025-01-30 18:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0030_portfolio_gender_portfolio_government_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
