# Generated by Django 5.1.1 on 2025-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0031_alter_portfolio_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
