# Generated by Django 5.1.1 on 2025-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0032_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount_sign',
            field=models.CharField(blank=True, choices=[('$', 'Dollar'), ('£', 'Pound Sterling'), ('€', 'Euro'), ('₣', 'Swiss Franc'), ('kr', 'Danish Krone'), ('kr', 'Swedish Krona'), ('kr', 'Norwegian Krone'), ('zł', 'Polish Zloty'), ('₴', 'Ukrainian Hryvnia'), ('лв', 'Bulgarian Lev'), ('Ft', 'Hungarian Forint'), ('lei', 'Romanian Leu'), ('₺', 'Turkish Lira'), ('руб', 'Russian Ruble'), ('Kč', 'Czech Koruna'), ('kn', 'Croatian Kuna'), ('RSD', 'Serbian Dinar'), ('MKD', 'Macedonian Denar'), ('ISK', 'Icelandic Krona')], default='$', max_length=5, null=True),
        ),
    ]
