# Generated by Django 5.1.1 on 2025-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0033_alter_transactions_amount_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Account Locked', 'Account Locked')], max_length=200, null=True),
        ),
    ]
