# Generated by Django 5.1.1 on 2025-03-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0034_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_email_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
