# Generated by Django 5.2.1 on 2025-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0035_portfolio_client_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='account_status',
            field=models.CharField(blank=True, choices=[('active', 'Active (Normal Transactions)'), ('pending_review', 'Pending Review'), ('on_hold', 'On Hold (Limited Transactions)'), ('locked', 'Account Locked')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
