# Generated by Django 5.2.1 on 2025-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0036_portfolio_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='account_status',
            field=models.CharField(blank=True, choices=[('active', 'Active (Normal Transactions)'), ('pending_review', 'Pending Review'), ('on_hold', 'On Hold (Limited Transactions)'), ('locked', 'Account Locked'), ('imf_locked', 'IMF Locked')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Account Locked', 'Account Locked'), ('Imf Locked', 'Imf Locked')], max_length=200, null=True),
        ),
    ]
