# Generated by Django 5.2.1 on 2025-09-05 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockwellbank', '0037_alter_portfolio_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
